"""Agregar columna precio_tintura

Revision ID: 7e9115e1673e
Revises: 6225f151b4aa
Create Date: 2025-01-05 16:31:46.815953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9115e1673e'
down_revision = '6225f151b4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_tintura', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('precio_tintura')

    # ### end Alembic commands ###
