"""Agregar columna precio_venta a la tabla PrecioColor

Revision ID: eac0c7a9b7f6
Revises: 7e9115e1673e
Create Date: 2025-01-05 17:32:42.336614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac0c7a9b7f6'
down_revision = '7e9115e1673e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_venta', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_color', schema=None) as batch_op:
        batch_op.drop_column('precio_venta')

    # ### end Alembic commands ###
